name: question_archive_mobile
description: Question Archive mobile reader with local SQLite storage.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  file_picker: ^10.3.3
  flutter_markdown: ^0.7.7+1
  path: ^1.9.1
  sqflite: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
